### ISSUE TITLE
Tasks with no names are allowed

### ISSUE THREAD

**Issue by BethGriggs** [BethGriggs/inse-7a#6]
Database should enforce Not Null for this, and an appropriate error message should be displayed.

**Comment by dimitarf** [comment]
it is enforced to be not null i think i reckon this goes to javascript validation as well

**Comment by BethGriggs** [comment]
Task Name is enforced not null but the database is still allowing it?  Any ideas why? Ithink this should be handled within the database and then have a JavaScript error message

**Comment by BethGriggs** [comment]
I have added a work around in PHP. This ideally should be handled elsewhere and with JavaScript validation. Will change to an enhancement.

**Comment by CalmArms** [comment]
Was this actually resolved? Think we should keep it open otherwise /s
