### ISSUE TITLE
Should numerical task names be allowed?

### ISSUE THREAD

**Issue by BethGriggs** [BethGriggs/inse-7a#7]
Discussion is needed whether we will allow purely numerical names

**Comment by CalmArms** [comment]
Yes we should allow them; while not allowing them to use purely numerical names would promote more appropriate task names, their could be really niche situations where they would prefer to use just number names.

Only example I can think of is someone planning to construct a detailed timeline of something and they would have year dates as task names or something.

**Comment by CalmArms** [comment]
No :(
